### ISSUE TITLE
Is there any way to pass "IGNORE" option to insert query?

### ISSUE THREAD

**Issue by cmsax** [t-tiger/gorm-bulk-insert#33]
I've tried `db.Set("gorm:insert_option", "IGNORE")` but it just append `IGNORE` to the SQL string like `insert into ... ... ... IGNORE`.

![](https://latina-1253549750.cos.ap-shanghai.myqcloud.com/essay/imgs/20200417175604.png)

**Comment by bombsimon** [comment]
If you want to create an `INSERT IGNORE ...` statement that's currently not possible. You can only use the tags for suffixes. If you want to ignore duplicate keys you can use `db.Set("gorm:insert_option", "ON DUPLICATE KEY IGNORE")`.

There was a PR for upsert in #28 but it got closed after some feedback. That would've allowed you to also perform `ON DUPLICATE KEY UPDATE ...`.

Sorry for promoting my own package, but [gorm-bulk](https://github.com/bombsimon/gorm-bulk) which is an alternative solutions where you can build your own query has support for all of this native.

```go
gormbulk.BulkInsert(db, yourRows)
gormbulk.BulkInsertIgnore(db, yourRows)
gormbulk.BulkInsertOnDuplicateKeyUpdate(db, yourRows)

// Or in chunk like this library
chunkSize := 3000
gormbulk.BulkExecChunk(db, yourRows, gormbulk.InsertIgnoreFunc, chunkSize)
```

Feel free to add a PR that implements any of these or use the alternative library. I wouldn't put too much time into this though since `gorm v2` is under active development and should be released within one to two months according to the developer.

**Comment by cmsax** [comment]
Thanks! I'll try gorm-bulk instead. 

Line 92 in `bulk_insert.go` indicates that it just append the options to the tail.
