### ISSUE TITLE
callbacks doesn't fired

### ISSUE THREAD

**Issue by bulwarkzero** [t-tiger/gorm-bulk-insert#35]
I used elastic APM in my project and every request to database is logged in APM, except a bulk_insert one. I figure out that registered callbacks for reference DB instance doesn't called.

**Comment by bombsimon** [comment]
Thanks for the issue!

I must admit that I'm not 100% familiar with the callback setup but I know that the method on the `scope` used to iterate over all registered is a private method which we cannot call from this code, see here: https://github.com/jinzhu/gorm/blob/master/scope.go#L859-L875. It also seems like the scope we get from the struct will set the parent scope (the `gorm.DB`) on a private field, see here: https://github.com/jinzhu/gorm/blob/master/main.go#L30

Even if it seems like we can get the parent context with [Callback()](https://github.com/jinzhu/gorm/blob/master/main.go#L144-L150) I don't see any way for us to actually invoke those since they're private as seen here: https://github.com/jinzhu/gorm/blob/master/callback.go#L8-L23.

I can try to dig into this later but I don't have much hope. Do you see any way that I'm missing regarding how we were to invoke any of these callback methods? Remember that we never use any `gorm` native methods such as `Create()` or `Save()`.

**Comment by t-tiger** [comment]
Although I don't fully understand the implementation of gorm's callback as well, looking at the gorm's source code, It appears not to be possible to call them from the outside package.

The reason why callbacks are not called is that this library only constructs SQL dynamically and executes it with the help of gorm's public methods.

it's theoretically possible to call callback methods such as `AfterSave` and `BeforeUpdate` through reflection without the help of gorm, but I think it's more important not to go off the rail of gorm, and prefer to call the public methods of gorm.
