### ISSUE TITLE
would this package support bulk update in the future?

### ISSUE THREAD

**Issue by itisbean** [t-tiger/gorm-bulk-insert#39]
the sql like :

UPDATE table_name
   SET a = CASE WHEN id = 1
                THEN 'something'
                WHEN id = 2
                THEN 'something else'
                WHEN id = 3
                THEN 'another'
           END
 WHERE id IN (1,2,3)
;

**Comment by bombsimon** [comment]
I don't think there's any plans to include this kind of feature, mainly because it's not a solution to the issue where `gorm` doesn't support bulk insert.

Support for upser/`ON DUPLICATE KEY` has been discussed, see the latest summary in #33 which mentions closed PRs and alternative implementations.

Other than that I see the end of this library getting closer while `gorm` is working it's way towards a v2.0 release with a total rewrite. You can follow the v2 development of `gorm` [here](https://github.com/jinzhu/gorm/issues/2886).

**Comment by itisbean** [comment]
ok, got this, thank you. I have already used v2.0 now.

**Comment by itisbean** [comment]
I use the "insert_option" with "ON DUPLICATE KEY UPDATE `column` VALUES (`column`)", and resovle this problem. Thank you!

**Comment by lopes-gustavo** [comment]
@itisbean how did you use the `insert_option`? I could not use it all.

```go
db.Set("gorm:insert_option", "ON DUPLICATE KEY IGNORE")
err := gormbulk.BulkInsert(db, slice, 3000)
```

But I still get `pq: duplicate key value violates unique constraint "name_unique_key"`

**Comment by itisbean** [comment]
> @itisbean how did you use the `insert_option`? I could not use it all.
> 
> ```go
> db.Set("gorm:insert_option", "ON DUPLICATE KEY IGNORE")
> err := gormbulk.BulkInsert(db, slice, 3000)
> ```
> 
> But I still get `pq: duplicate key value violates unique constraint "name_unique_key"`

I use it like this way:

gormbulk.BulkInsert(db.Set("gorm:insert_option", "ON DUPLICATE KEY UPDATE `field1` =  VALUES(`field1`), `field2` = VALUES(`field2`)"), slice, 3000)

**Comment by bombsimon** [comment]
@lopes-gustavo Most of the operations in `gorm` return a new pointer to the db handler so you need to re-assign it. With your code this should work:

```go
db = db.Set("gorm:insert_option", "ON DUPLICATE KEY IGNORE")
err := gormbulk.BulkInsert(db, slice, 3000)
```
