### ISSUE TITLE
you can update to the new version of gorm

### ISSUE THREAD

**Issue by pzentenoe** [t-tiger/gorm-bulk-insert#47]
gorm.io/gorm

**Comment by bombsimon** [comment]
I don't really see a need for this since the latest version of gorm released after moving to `gorm.io/gorm` already supports this.

I see that they still host v1 at `gorm.io/gorm` but so do they do on `github.com/jinzhu/gorm`. This one is a fork of `https://github.com/go-gorm/gorm` which is just no longer maintained (I guess maybe patches for v1)?

I think it's a good thing that people notices this, if they do they will probably just bump to latest gorm and can drop this package.

Anything I'm missing regarding why we should change the dependency source?

**Comment by bombsimon** [comment]
Closing this as there is no response from the author. Please let me know if you want me to re-open this again.
